CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%socialhub_hashtags` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `hashtag` varchar(50) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;